/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2020-06-01 06:12:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web.responsive.checkout.multi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkoutOrderSummary_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("ycommerce:sanitizeHTML", de.hybris.platform.acceleratorstorefrontcommons.tags.HTMLSanitizer.class, "sanitizeHTML", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(21);
    _jspx_dependants.put("jar:file:/C:/hybris1905/hybris/bin/platform/ext/core/lib/spring-webmvc-5.1.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1554000908000L));
    _jspx_dependants.put("/WEB-INF/tags/shared/theme/image.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/order/appliedVouchers.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("jar:file:/C:/hybris1905/hybris/bin/modules/base-accelerator/yacceleratorstorefront/web/webroot/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1308107170000L));
    _jspx_dependants.put("/WEB-INF/tags/shared/theme/implicit.tld", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1590990527093L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/checkout/multi/deliveryCartItems.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/common/implicit.tld", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/checkout/multi/pickupCartItems.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("file:/C:/hybris1905/hybris/bin/platform/ext/core/lib/spring-webmvc-5.1.6.RELEASE.jar", Long.valueOf(1558680496000L));
    _jspx_dependants.put("/WEB-INF/tags/shared/format/implicit.tld", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/checkout/multi/paymentInfo.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/product/productPrimaryImage.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/shared/format/price.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/checkout/multi/orderTotals.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("jar:file:/C:/hybris1905/hybris/bin/platform/ext/core/lib/spring-webmvc-5.1.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1554000908000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/grid/gridWrapper.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/common/tld/ycommercetags.tld", Long.valueOf(1558679600000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/common/configurationInfos.tag", Long.valueOf(1558679600000L));
    _jspx_dependants.put("jar:file:/C:/hybris1905/hybris/bin/modules/base-accelerator/yacceleratorstorefront/web/webroot/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308107170000L));
    _jspx_dependants.put("/WEB-INF/tags/responsive/product/implicit.tld", Long.valueOf(1558679600000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fhtmlEscape_0026_005fdefaultHtmlEscape_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fid_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fcheckbox_0026_005fpath_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fvar_005fhtmlEscape_005fcode_005farguments_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private de.hybris.platform.commercefacades.order.data.CartData cartData;
  private java.lang.Boolean showDeliveryAddress;
  private java.lang.Boolean showPaymentInfo;
  private java.lang.Boolean showTax;
  private java.lang.Boolean showTaxEstimate;

  public de.hybris.platform.commercefacades.order.data.CartData getCartData() {
    return this.cartData;
  }

  public void setCartData(de.hybris.platform.commercefacades.order.data.CartData cartData) {
    this.cartData = cartData;
    jspContext.setAttribute("cartData", cartData);
  }

  public java.lang.Boolean getShowDeliveryAddress() {
    return this.showDeliveryAddress;
  }

  public void setShowDeliveryAddress(java.lang.Boolean showDeliveryAddress) {
    this.showDeliveryAddress = showDeliveryAddress;
    jspContext.setAttribute("showDeliveryAddress", showDeliveryAddress);
  }

  public java.lang.Boolean getShowPaymentInfo() {
    return this.showPaymentInfo;
  }

  public void setShowPaymentInfo(java.lang.Boolean showPaymentInfo) {
    this.showPaymentInfo = showPaymentInfo;
    jspContext.setAttribute("showPaymentInfo", showPaymentInfo);
  }

  public java.lang.Boolean getShowTax() {
    return this.showTax;
  }

  public void setShowTax(java.lang.Boolean showTax) {
    this.showTax = showTax;
    jspContext.setAttribute("showTax", showTax);
  }

  public java.lang.Boolean getShowTaxEstimate() {
    return this.showTaxEstimate;
  }

  public void setShowTaxEstimate(java.lang.Boolean showTaxEstimate) {
    this.showTaxEstimate = showTaxEstimate;
    jspContext.setAttribute("showTaxEstimate", showTaxEstimate);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _005fjspx_005ftagPool_005fspring_005fhtmlEscape_0026_005fdefaultHtmlEscape_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fid_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fform_005fcheckbox_0026_005fpath_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fvar_005fhtmlEscape_005fcode_005farguments_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fhtmlEscape_0026_005fdefaultHtmlEscape_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fid_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005fcheckbox_0026_005fpath_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fvar_005fhtmlEscape_005fcode_005farguments_005fnobody.release();
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getCartData() != null ) 
      _jspx_page_context.setAttribute("cartData", getCartData());
    if( getShowDeliveryAddress() != null ) 
      _jspx_page_context.setAttribute("showDeliveryAddress", getShowDeliveryAddress());
    if( getShowPaymentInfo() != null ) 
      _jspx_page_context.setAttribute("showPaymentInfo", getShowPaymentInfo());
    if( getShowTax() != null ) 
      _jspx_page_context.setAttribute("showTax", getShowTax());
    if( getShowTaxEstimate() != null ) 
      _jspx_page_context.setAttribute("showTaxEstimate", getShowTaxEstimate());

    try {
      if (_jspx_meth_spring_005fhtmlEscape_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("<div class=\"checkout-summary-headline hidden-xs\">\n");
      out.write("    ");
      if (_jspx_meth_spring_005ftheme_005f0(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("<div class=\"checkout-order-summary\">\n");
      out.write("    ");
      if (_jspx_meth_ycommerce_005ftestId_005f0(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"visible-xs clearfix\">\n");
      out.write("    ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("</div>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
      _jspDestroy();
    }
  }

  private boolean _jspx_meth_spring_005fhtmlEscape_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:htmlEscape
    org.springframework.web.servlet.tags.HtmlEscapeTag _jspx_th_spring_005fhtmlEscape_005f0 = (org.springframework.web.servlet.tags.HtmlEscapeTag) _005fjspx_005ftagPool_005fspring_005fhtmlEscape_0026_005fdefaultHtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.HtmlEscapeTag.class);
    boolean _jspx_th_spring_005fhtmlEscape_005f0_reused = false;
    try {
      _jspx_th_spring_005fhtmlEscape_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhtmlEscape_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(16,0) name = defaultHtmlEscape type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhtmlEscape_005f0.setDefaultHtmlEscape(true);
      int[] _jspx_push_body_count_spring_005fhtmlEscape_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhtmlEscape_005f0 = _jspx_th_spring_005fhtmlEscape_005f0.doStartTag();
        if (_jspx_th_spring_005fhtmlEscape_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhtmlEscape_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhtmlEscape_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhtmlEscape_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhtmlEscape_0026_005fdefaultHtmlEscape_005fnobody.reuse(_jspx_th_spring_005fhtmlEscape_005f0);
      _jspx_th_spring_005fhtmlEscape_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhtmlEscape_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fhtmlEscape_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(18,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/checkout/multi/summary/placeOrder");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(18,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("placeOrderUrl");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(18,0) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setHtmlEscape(false);
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f1_reused = false;
    try {
      _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(19,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setValue("/checkout/multi/termsAndConditions");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(19,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setVar("getTermsAndConditionsUrl");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(19,0) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setHtmlEscape(false);
      int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
        if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fhtmlEscape_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
      _jspx_th_spring_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005ftheme_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:theme
    org.springframework.web.servlet.tags.ThemeTag _jspx_th_spring_005ftheme_005f0 = (org.springframework.web.servlet.tags.ThemeTag) _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.ThemeTag.class);
    boolean _jspx_th_spring_005ftheme_005f0_reused = false;
    try {
      _jspx_th_spring_005ftheme_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005ftheme_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(22,4) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f0.setCode("checkout.multi.order.summary");
      int[] _jspx_push_body_count_spring_005ftheme_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005ftheme_005f0 = _jspx_th_spring_005ftheme_005f0.doStartTag();
        if (_jspx_th_spring_005ftheme_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005ftheme_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005ftheme_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005ftheme_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005ftheme_005f0);
      _jspx_th_spring_005ftheme_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ftheme_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005ftheme_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ycommerce_005ftestId_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ycommerce:testId
    de.hybris.platform.yacceleratorstorefront.tags.TestIdTag _jspx_th_ycommerce_005ftestId_005f0 = new de.hybris.platform.yacceleratorstorefront.tags.TestIdTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ycommerce_005ftestId_005f0);
    try {
      _jspx_th_ycommerce_005ftestId_005f0.setJspContext(_jspx_page_context);
      _jspx_th_ycommerce_005ftestId_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(25,4) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ycommerce_005ftestId_005f0.setCode("orderSummary");
      _jspx_th_ycommerce_005ftestId_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_ycommerce_005ftestId_005f0, null));
      _jspx_th_ycommerce_005ftestId_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ycommerce_005ftestId_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_multi_002dcheckout_005fdeliveryCartItems_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  multi-checkout:deliveryCartItems
    org.apache.jsp.tag.web.responsive.checkout.multi.deliveryCartItems_tag _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0 = new org.apache.jsp.tag.web.responsive.checkout.multi.deliveryCartItems_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0);
    try {
      _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0.setJspContext(_jspx_page_context);
      _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0.setParent(_jspx_parent);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(26,8) name = cartData type = de.hybris.platform.commercefacades.order.data.CartData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0.setCartData((de.hybris.platform.commercefacades.order.data.CartData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData}", de.hybris.platform.commercefacades.order.data.CartData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(26,8) name = showDeliveryAddress type = java.lang.Boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0.setShowDeliveryAddress((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${showDeliveryAddress}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      _jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_multi_002dcheckout_005fdeliveryCartItems_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(28,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(28,8) '${cartData.pickupOrderGroups}'",_jsp_getExpressionFactory().createValueExpression(this.getJspContext().getELContext(),"${cartData.pickupOrderGroups}",java.lang.Object.class)).getValue(this.getJspContext().getELContext()));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(28,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("groupData");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(28,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            if (_jspx_meth_multi_002dcheckout_005fpickupCartItems_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_multi_002dcheckout_005fpickupCartItems_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  multi-checkout:pickupCartItems
    org.apache.jsp.tag.web.responsive.checkout.multi.pickupCartItems_tag _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0 = new org.apache.jsp.tag.web.responsive.checkout.multi.pickupCartItems_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_multi_002dcheckout_005fpickupCartItems_005f0);
    try {
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.setJspContext(_jspx_page_context);
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.setParent(_jspx_th_c_005fforEach_005f0);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(29,12) name = cartData type = de.hybris.platform.commercefacades.order.data.CartData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.setCartData((de.hybris.platform.commercefacades.order.data.CartData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData}", de.hybris.platform.commercefacades.order.data.CartData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(29,12) name = groupData type = de.hybris.platform.commercefacades.order.data.OrderEntryGroupData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.setGroupData((de.hybris.platform.commercefacades.order.data.OrderEntryGroupData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${groupData}", de.hybris.platform.commercefacades.order.data.OrderEntryGroupData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(29,12) name = showHead type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.setShowHead(new java.lang.Boolean(true));
      _jspx_th_multi_002dcheckout_005fpickupCartItems_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_multi_002dcheckout_005fpickupCartItems_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_order_005fappliedVouchers_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  order:appliedVouchers
    org.apache.jsp.tag.web.responsive.order.appliedVouchers_tag _jspx_th_order_005fappliedVouchers_005f0 = new org.apache.jsp.tag.web.responsive.order.appliedVouchers_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_order_005fappliedVouchers_005f0);
    try {
      _jspx_th_order_005fappliedVouchers_005f0.setJspContext(_jspx_page_context);
      _jspx_th_order_005fappliedVouchers_005f0.setParent(_jspx_parent);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(32,8) name = order type = de.hybris.platform.commercefacades.order.data.AbstractOrderData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_order_005fappliedVouchers_005f0.setOrder((de.hybris.platform.commercefacades.order.data.AbstractOrderData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData}", de.hybris.platform.commercefacades.order.data.AbstractOrderData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      _jspx_th_order_005fappliedVouchers_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_order_005fappliedVouchers_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_multi_002dcheckout_005fpaymentInfo_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  multi-checkout:paymentInfo
    org.apache.jsp.tag.web.responsive.checkout.multi.paymentInfo_tag _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0 = new org.apache.jsp.tag.web.responsive.checkout.multi.paymentInfo_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_multi_002dcheckout_005fpaymentInfo_005f0);
    try {
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.setJspContext(_jspx_page_context);
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.setParent(_jspx_parent);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(34,8) name = cartData type = de.hybris.platform.commercefacades.order.data.CartData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.setCartData((de.hybris.platform.commercefacades.order.data.CartData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData}", de.hybris.platform.commercefacades.order.data.CartData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(34,8) name = paymentInfo type = de.hybris.platform.commercefacades.order.data.CCPaymentInfoData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.setPaymentInfo((de.hybris.platform.commercefacades.order.data.CCPaymentInfoData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData.paymentInfo}", de.hybris.platform.commercefacades.order.data.CCPaymentInfoData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(34,8) name = showPaymentInfo type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.setShowPaymentInfo((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${showPaymentInfo}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      _jspx_th_multi_002dcheckout_005fpaymentInfo_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_multi_002dcheckout_005fpaymentInfo_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_multi_002dcheckout_005forderTotals_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  multi-checkout:orderTotals
    org.apache.jsp.tag.web.responsive.checkout.multi.orderTotals_tag _jspx_th_multi_002dcheckout_005forderTotals_005f0 = new org.apache.jsp.tag.web.responsive.checkout.multi.orderTotals_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_multi_002dcheckout_005forderTotals_005f0);
    try {
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.setJspContext(_jspx_page_context);
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.setParent(_jspx_parent);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(37,8) name = cartData type = de.hybris.platform.commercefacades.order.data.CartData reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.setCartData((de.hybris.platform.commercefacades.order.data.CartData) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartData}", de.hybris.platform.commercefacades.order.data.CartData.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(37,8) name = showTaxEstimate type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.setShowTaxEstimate((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${showTaxEstimate}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(37,8) name = showTax type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.setShowTax((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${showTax}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      _jspx_th_multi_002dcheckout_005forderTotals_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_multi_002dcheckout_005forderTotals_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fid_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(42,4) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeOrderUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(42,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("placeOrderForm1");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(42,4) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setModelAttribute("placeOrderForm");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(42,4) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "place-order-form col-xs-12");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<div class=\"checkbox\">\n");
            out.write("            <label> ");
            if (_jspx_meth_form_005fcheckbox_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            if (_jspx_meth_spring_005ftheme_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ycommerce:sanitizeHTML(termsAndConditionsHtml)}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), _jspx_fnmap_1));
            out.write("</label>\n");
            out.write("        </div>\n");
            out.write("\n");
            out.write("        <button id=\"placeOrder\" type=\"submit\" class=\"btn btn-primary btn-place-order btn-block\">\n");
            out.write("            ");
            if (_jspx_meth_spring_005ftheme_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("</button>\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fid_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fcheckbox_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_form_005fcheckbox_005f0 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fform_005fcheckbox_0026_005fpath_005fid_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_form_005fcheckbox_005f0_reused = false;
    try {
      _jspx_th_form_005fcheckbox_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fcheckbox_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(44,20) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fcheckbox_005f0.setId("Terms1");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(44,20) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fcheckbox_005f0.setPath("termsCheck");
      int[] _jspx_push_body_count_form_005fcheckbox_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fcheckbox_005f0 = _jspx_th_form_005fcheckbox_005f0.doStartTag();
        if (_jspx_th_form_005fcheckbox_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fcheckbox_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fcheckbox_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fcheckbox_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fcheckbox_0026_005fpath_005fid_005fnobody.reuse(_jspx_th_form_005fcheckbox_005f0);
      _jspx_th_form_005fcheckbox_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fcheckbox_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fcheckbox_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005ftheme_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:theme
    org.springframework.web.servlet.tags.ThemeTag _jspx_th_spring_005ftheme_005f1 = (org.springframework.web.servlet.tags.ThemeTag) _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fvar_005fhtmlEscape_005fcode_005farguments_005fnobody.get(org.springframework.web.servlet.tags.ThemeTag.class);
    boolean _jspx_th_spring_005ftheme_005f1_reused = false;
    try {
      _jspx_th_spring_005ftheme_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005ftheme_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(45,16) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f1.setVar("termsAndConditionsHtml");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(45,16) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f1.setCode("checkout.summary.placeOrder.readTermsAndConditions");
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(45,16) name = arguments type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f1.setArguments((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(getTermsAndConditionsUrl)}", java.lang.Object.class, (javax.servlet.jsp.PageContext)this.getJspContext(), _jspx_fnmap_0));
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(45,16) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f1.setHtmlEscape(false);
      int[] _jspx_push_body_count_spring_005ftheme_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005ftheme_005f1 = _jspx_th_spring_005ftheme_005f1.doStartTag();
        if (_jspx_th_spring_005ftheme_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005ftheme_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005ftheme_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005ftheme_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fvar_005fhtmlEscape_005fcode_005farguments_005fnobody.reuse(_jspx_th_spring_005ftheme_005f1);
      _jspx_th_spring_005ftheme_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ftheme_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005ftheme_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005ftheme_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:theme
    org.springframework.web.servlet.tags.ThemeTag _jspx_th_spring_005ftheme_005f2 = (org.springframework.web.servlet.tags.ThemeTag) _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.ThemeTag.class);
    boolean _jspx_th_spring_005ftheme_005f2_reused = false;
    try {
      _jspx_th_spring_005ftheme_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005ftheme_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/tags/responsive/checkout/multi/checkoutOrderSummary.tag(51,12) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005ftheme_005f2.setCode("checkout.summary.placeOrder");
      int[] _jspx_push_body_count_spring_005ftheme_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005ftheme_005f2 = _jspx_th_spring_005ftheme_005f2.doStartTag();
        if (_jspx_th_spring_005ftheme_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005ftheme_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005ftheme_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005ftheme_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005ftheme_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005ftheme_005f2);
      _jspx_th_spring_005ftheme_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ftheme_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005ftheme_005f2_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_multi_002dcheckout_005fdeliveryCartItems_005f0(_jspx_parent, _jspx_page_context))
        return true;
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      if (_jspx_meth_order_005fappliedVouchers_005f0(_jspx_parent, _jspx_page_context))
        return true;
      if (_jspx_meth_multi_002dcheckout_005fpaymentInfo_005f0(_jspx_parent, _jspx_page_context))
        return true;
      if (_jspx_meth_multi_002dcheckout_005forderTotals_005f0(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
